#ifndef MOONLANDER_TILES_H
#define MOONLANDER_TILES_H

enum tile {
    TILE_NONE,
    TILE_ROCK_0,
    TILE_ROCK_1,
    TILE_ROCK_2,
    TILE_ROCK_3,
    TILE_EARTH,
    TILE_STARS,
    TILE_STARS_EARTH
};

#endif